---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy1
  template:
    metadata:
      labels:
        app: swiggy1
    spec:
      containers:
      - name: swiggy1
        image: jeyakrishnan/swiggy1-clone:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
